name: GH Actions workflow
on:
  push:
    branches:
      - main
  schedule:
    - cron: "06 0 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  call-build-externals:
    uses: ./.github/workflows/build-externals.yml
  call-mkdocs:
    if: ${{ always() }}
    needs: call-build-externals
    uses: ./.github/workflows/mkdocs.yml
