name: GH Actions workflow
on:
  push:
    branches:
      - master 
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  call-changelog:
    uses: ./.github/workflows/changelog.yml
  call-mkdocs:
    if: ${{ always() }}
    needs: call-changelog
    uses: ./.github/workflows/mkdocs.yml
